mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: ecommerce
  url: ${DATABASE_MYSQL_URL:localhost:3306}

amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

elasticsearch:
  host: ${ELASTICSEARCH_HOST:http://localhost:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:elastic}

kafka:
  consumers:
    products:
      auto-create-topics: true