aws-cloud:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucketName: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}

storage:
  aws:
    s3:
      product:
        providerUrl: https://${AWS_S3_BUCKET_NAME}.s3.${AWS_REGION}.amazonaws.com

amqp:
  admin:
    auto-create: false
  queues:
    account-created:
      exchange: account.events
      routing-key: account.created
      queue: account.created.queue
    account-deleted:
      exchange: account.events
      routing-key: account.deleted
      queue: account.deleted.queue
    email-queue:
      exchange: email.events
      routing-key: email.send
      queue: email.queue

kafka:
  auto-create-topics: true
  bootstrap-servers: localhost:9092
  pool-timeout: 1_000
  auto-commit: false
  consumers:
    categories:
      auto-offset-reset: earliest
      concurrency: 1
      id: kafka-listener-categories
      topics: category-topic
      group-id: categories-group
    products:
      auto-offset-reset: earliest
      concurrency: 1
      id: kafka-listener-products
      topics: product-topic
      group-id: products-group
      max-attempts: 4
      auto-create-topics: false
    inventories:
      auto-offset-reset: earliest
      concurrency: 1
      id: kafka-listener-inventories
      topics: inventory-topic
      group-id: inventories-group
      max-attempts: 4
      auto-create-topics: false

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    dynamic: ${amqp.admin.auto-create}
    host: ${amqp.host}
    port: ${amqp.port}
    username: ${amqp.username}
    password: ${amqp.password}
  data:
    redis:
      database: 0
      host: ${redis.host}
      port: ${redis.port}
  elasticsearch:
    uris: ${elasticsearch.host}
    username: ${elasticsearch.username}
    password: ${elasticsearch.password}
    connect-timeout: 250
    socket-timeout: 1_0000