amqp:
  admin:
    auto-create: false
  host: localhost
  port: 5672
  username: ecommerce_users_admin
  password: ecommerce_users_admin123456

redis:
  host: localhost
  port: 6380

neo4j:
  host: localhost
  port: 7687
  username: neo4j
  password: 123456789

logging:
  level:
    com.kaua.ecommerce.infrastructure: DEBUG

server:
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  flyway:
    enabled: true