redis:
  host: localhost
  port: 6381

neo4j:
  host: localhost
  port: 7475
  username: neo4j
  password: 123456789

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:ecommerce;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true