amqp:
  admin:
    auto-create: false
  host: localhost
  port: 5672
  username: ecommerce_users_admin
  password: ecommerce_users_admin123456

redis:
  host: localhost
  port: 6380

elasticsearch:
  host: http://localhost:9200
  username: elastic
  password: elastic

kafka:
  consumers:
    products:
      auto-create-topics: true


logging:
  level:
    com.kaua.ecommerce.infrastructure: DEBUG

server:
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  flyway:
    enabled: true