version: '3.8'

services:
  mysql:
    container_name: ecommerce-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce
    security_opt:
      - seccomp:unconfined
    ports:
      - 3307:3306
    networks:
      - ecommerce_network

  redis:
    container_name: ecommerce-redis
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - ecommerce_network

  elasticsearch:
    container_name: ecommerce-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "bootstrap.memory_lock=true"
      - "cluster.name=ecommerce"
      - "node.name=es01"
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ecommerce_network

networks:
  ecommerce_network: