name: CI - Run tests after push

on:
  push:
    branches:
      - feature/*
      - refactor/*
      - hotfix/*
      - bugfix/*
      - release/*
      - fix/*
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute unitTests
        run: ./gradlew unitTests

      - name: Execute heavyIntegrationTests
        run: ./gradlew heavyIntegrationTests

      - name: Execute IntegrationTests
        run: ./gradlew integrationTests